-- V10__schedules_phases_dependencies.sql
-- Smart project schedule (project.txt section 5 "Cronograma inteligente";
-- section 9 schema: Propuesta -> Cronograma -> Fase, plus Dependencia).
-- Tables and columns are in English; only content rows may be in Spanish.
--
-- A schedule belongs to exactly one proposal (UNIQUE proposal_id) and turns the
-- proposal's estimated hours into a phased timeline. Each phase keeps the share
-- of the project's hours it consumes (hours_share) and the derived duration in
-- weeks; start_week/end_week are its derived placement on the timeline.
--
-- Durations derive from the estimated hours and phases shift in cascade: when a
-- human edits the quoted hours at approval time, the proposal recomputes every
-- phase duration and re-places each downstream phase through the dependency
-- graph. weeks/start_week/end_week are written by the domain, not stored
-- GENERATED columns, for the same H2/PostgreSQL portability reason given in V6
-- and V8 (the division/ceiling plus a graph walk cannot be expressed portably).
--
-- phase_order stores the planned sequence used as a deterministic tie-break,
-- while phase_dependencies store the finish-to-start constraints that actually
-- drive the cascade. Acyclicity has no portable SQL constraint, so the Schedule
-- aggregate rejects a cycle in the domain before any row is written.

CREATE TABLE schedules (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id    BIGINT NOT NULL,
    -- Total estimated hours the proposal quotes; the phases divide this up.
    total_hours    NUMERIC(10, 2) NOT NULL,
    -- Planning capacity used to turn hours into weeks (e.g. 40 h/week).
    hours_per_week NUMERIC(6, 2) NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    -- One schedule per proposal; it is a composed child and shares its lifecycle.
    CONSTRAINT fk_schedules_proposal FOREIGN KEY (proposal_id)
        REFERENCES proposals (id) ON DELETE CASCADE,
    CONSTRAINT uq_schedules_proposal UNIQUE (proposal_id),
    CONSTRAINT ck_schedules_total_hours CHECK (total_hours >= 0),
    CONSTRAINT ck_schedules_hours_per_week CHECK (hours_per_week > 0)
);

CREATE TABLE phases (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id  BIGINT NOT NULL,
    name         VARCHAR(120) NOT NULL,
    -- Fraction of the project hours this phase consumes, in (0, 1].
    hours_share  NUMERIC(6, 4) NOT NULL,
    -- Derived duration; recomputed on every hour change.
    weeks        INTEGER NOT NULL,
    -- Planned sequence ("Fase" order); `order` itself is a reserved SQL word.
    phase_order  INTEGER NOT NULL,
    -- Derived timeline placement; shifted in cascade with upstream durations.
    start_week   INTEGER NOT NULL,
    end_week     INTEGER NOT NULL,
    CONSTRAINT fk_phases_schedule FOREIGN KEY (schedule_id)
        REFERENCES schedules (id) ON DELETE CASCADE,
    CONSTRAINT uq_phases_schedule_order UNIQUE (schedule_id, phase_order),
    CONSTRAINT ck_phases_hours_share CHECK (hours_share > 0 AND hours_share <= 1),
    CONSTRAINT ck_phases_weeks CHECK (weeks >= 1),
    CONSTRAINT ck_phases_week_range CHECK (start_week >= 1 AND end_week >= start_week)
);

CREATE INDEX idx_phases_schedule_id ON phases (schedule_id);

CREATE TABLE phase_dependencies (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- The dependent phase...
    phase_id            BIGINT NOT NULL,
    -- ...and the phase it must wait for (finish-to-start).
    depends_on_phase_id BIGINT NOT NULL,
    -- A dependency is a composed child of its dependent phase, so removing the
    -- phase (or its schedule) removes the edge. Deleting the prerequisite phase
    -- also drops the edge via this second cascade.
    CONSTRAINT fk_phase_dependencies_phase FOREIGN KEY (phase_id)
        REFERENCES phases (id) ON DELETE CASCADE,
    CONSTRAINT fk_phase_dependencies_depends_on FOREIGN KEY (depends_on_phase_id)
        REFERENCES phases (id) ON DELETE CASCADE,
    CONSTRAINT uq_phase_dependencies_edge UNIQUE (phase_id, depends_on_phase_id),
    -- A phase can never depend on itself; longer cycles are rejected in domain.
    CONSTRAINT ck_phase_dependencies_not_self CHECK (phase_id <> depends_on_phase_id)
);

CREATE INDEX idx_phase_dependencies_phase_id ON phase_dependencies (phase_id);
CREATE INDEX idx_phase_dependencies_depends_on_id ON phase_dependencies (depends_on_phase_id);
