-- V11__contracts_clauses.sql
-- Contract + clauses (project.txt section 4 acceptance flow; section 9 schema:
-- Propuesta -> Contrato -> Clausula).
-- Tables and columns are in English; only content rows may be in Spanish.
--
-- A contract is the legal document behind a proposal. It is generated as a
-- DRAFT together with the proposal and only becomes ISSUED on acceptance. The
-- proposal<->contract relationship is one-to-one (UNIQUE proposal_id) and the
-- contract is a composed child of the proposal: deleting the proposal removes
-- the contract and, in turn, its clauses (ON DELETE CASCADE).
--
-- Payment is its own aggregate and table in a later issue; it leaves no trace
-- on the contract row. The paired CHECK constraint makes the issue rule hold
-- at the database level too: a DRAFT carries no issue evidence, an ISSUED row
-- cannot exist without it. issued_at is written by the domain, not a generated
-- column, so the acceptance timestamp is explicit and testable.
--
-- clauses.clause_order is the display order ("order" is a reserved SQL word).
-- Clauses are composed children of the contract and share its lifecycle, so a
-- contract id can never be orphaned by a deleted clause.

CREATE TABLE contracts (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id       BIGINT NOT NULL,
    status            VARCHAR(20) NOT NULL,
    -- Null until the contract is issued on acceptance.
    issued_at         TIMESTAMP WITH TIME ZONE,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    -- One contract per proposal; it is a composed child and shares its lifecycle.
    CONSTRAINT fk_contracts_proposal FOREIGN KEY (proposal_id)
        REFERENCES proposals (id) ON DELETE CASCADE,
    CONSTRAINT uq_contracts_proposal UNIQUE (proposal_id),
    CONSTRAINT ck_contracts_status CHECK (status IN ('DRAFT', 'ISSUED')),
    -- DRAFT: no issue evidence yet. ISSUED: issued_at present. This is what
    -- makes "final ISSUED only on acceptance" a stored invariant.
    CONSTRAINT ck_contracts_issue CHECK (
        (status = 'DRAFT'
            AND issued_at IS NULL)
        OR (status = 'ISSUED'
            AND issued_at IS NOT NULL))
);

CREATE INDEX idx_contracts_proposal_id ON contracts (proposal_id);
CREATE INDEX idx_contracts_status ON contracts (status);

CREATE TABLE clauses (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id  BIGINT NOT NULL,
    -- Display order; "order" is reserved, hence clause_order.
    clause_order INTEGER NOT NULL,
    text         TEXT NOT NULL,
    CONSTRAINT fk_clauses_contract FOREIGN KEY (contract_id)
        REFERENCES contracts (id) ON DELETE CASCADE,
    CONSTRAINT uq_clauses_contract_order UNIQUE (contract_id, clause_order),
    CONSTRAINT ck_clauses_order CHECK (clause_order >= 1),
    CONSTRAINT ck_clauses_text CHECK (LENGTH(TRIM(text)) > 0)
);

CREATE INDEX idx_clauses_contract_id ON clauses (contract_id);
