-- V11__contracts_clauses.sql
-- Contract + clauses (project.txt section 4 payment flow; section 9 schema:
-- Propuesta -> Contrato -> Clausula).
-- Tables and columns are in English; only content rows may be in Spanish.
--
-- A contract is the legal document behind a proposal. It is generated as a
-- DRAFT together with the proposal and only becomes ISSUED once the simulated
-- payment is recorded. The proposal<->contract relationship is one-to-one
-- (UNIQUE proposal_id) and the contract is a composed child of the proposal:
-- deleting the proposal removes the contract and, in turn, its clauses
-- (ON DELETE CASCADE).
--
-- The simulated payment leaves its receipt on the contract row
-- (payment_reference / paid_amount / paid_at). The dedicated Payment
-- aggregate and its table are their own issue; issue #11 only needs this
-- evidence so the domain can guarantee "final ISSUED only after payment". The
-- paired CHECK constraint makes that rule hold at the database level too: a
-- DRAFT carries no issue/payment evidence, an ISSUED row cannot exist without
-- it. issued_at is written by the domain, not a generated column, so the
-- acceptance timestamp is explicit and testable.
--
-- clauses.clause_order is the display order ("order" is a reserved SQL word).
-- Clauses are composed children of the contract and share its lifecycle, so a
-- contract id can never be orphaned by a deleted clause.

CREATE TABLE contracts (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id       BIGINT NOT NULL,
    status            VARCHAR(20) NOT NULL,
    -- Null until the contract is issued after the simulated payment.
    issued_at         TIMESTAMP WITH TIME ZONE,
    -- Simulated payment evidence recorded atomically with the ISSUED flip.
    payment_reference VARCHAR(80),
    paid_amount       NUMERIC(12, 2),
    paid_at           TIMESTAMP WITH TIME ZONE,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    -- One contract per proposal; it is a composed child and shares its lifecycle.
    CONSTRAINT fk_contracts_proposal FOREIGN KEY (proposal_id)
        REFERENCES proposals (id) ON DELETE CASCADE,
    CONSTRAINT uq_contracts_proposal UNIQUE (proposal_id),
    CONSTRAINT ck_contracts_status CHECK (status IN ('DRAFT', 'ISSUED')),
    -- DRAFT: no issue/payment evidence yet. ISSUED: all of it present. This is
    -- what makes "final ISSUED only after simulated payment" a stored invariant.
    CONSTRAINT ck_contracts_issue CHECK (
        (status = 'DRAFT'
            AND issued_at IS NULL
            AND payment_reference IS NULL
            AND paid_amount IS NULL
            AND paid_at IS NULL)
        OR (status = 'ISSUED'
            AND issued_at IS NOT NULL
            AND payment_reference IS NOT NULL
            AND paid_amount IS NOT NULL
            AND paid_at IS NOT NULL)),
    CONSTRAINT ck_contracts_paid_amount CHECK (paid_amount IS NULL OR paid_amount >= 0)
);

CREATE INDEX idx_contracts_proposal_id ON contracts (proposal_id);
CREATE INDEX idx_contracts_status ON contracts (status);

CREATE TABLE clauses (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id  BIGINT NOT NULL,
    -- Display order; "order" is reserved, hence clause_order.
    clause_order INTEGER NOT NULL,
    text         TEXT NOT NULL,
    CONSTRAINT fk_clauses_contract FOREIGN KEY (contract_id)
        REFERENCES contracts (id) ON DELETE CASCADE,
    CONSTRAINT uq_clauses_contract_order UNIQUE (contract_id, clause_order),
    CONSTRAINT ck_clauses_order CHECK (clause_order >= 1),
    CONSTRAINT ck_clauses_text CHECK (LENGTH(TRIM(text)) > 0)
);

CREATE INDEX idx_clauses_contract_id ON clauses (contract_id);
