--
-- One row per accepted proposal transition (project.txt section 6 pattern 9: State).
-- The domain writes a row only after the current State accepts the event.
-- This audit trail also supports analytics such as time to send and acceptance rate;
-- therefore (to_status, changed_at) is indexed.
--
CREATE TABLE proposal_status_changes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id BIGINT NOT NULL,
    from_status VARCHAR(20) NOT NULL,
    to_status VARCHAR(20) NOT NULL,
    changed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_proposal_status_changes_proposal FOREIGN KEY (proposal_id)
        REFERENCES proposals (id) ON DELETE CASCADE,
    CONSTRAINT ck_proposal_status_changes_from_status CHECK (from_status IN (
        'RECEIVED', 'ANALYZING', 'QUOTED', 'IN_REVIEW', 'SENT',
        'NEGOTIATING', 'ACCEPTED', 'CONTRACT_ISSUED', 'REJECTED', 'EXPIRED')),
    CONSTRAINT ck_proposal_status_changes_to_status CHECK (to_status IN (
        'RECEIVED', 'ANALYZING', 'QUOTED', 'IN_REVIEW', 'SENT',
        'NEGOTIATING', 'ACCEPTED', 'CONTRACT_ISSUED', 'REJECTED', 'EXPIRED')),
    CONSTRAINT ck_proposal_status_changes_distinct CHECK (from_status <> to_status)
);

CREATE INDEX idx_proposal_status_changes_proposal_id ON proposal_status_changes (proposal_id);
CREATE INDEX idx_proposal_status_changes_to_status_changed_at
    ON proposal_status_changes (to_status, changed_at);
