--
-- Notifications audit proposal lifecycle events (project.txt section 6: Observer).
-- Each observer writes one row in the proposal transition transaction. Channel
-- deliberately has no CHECK list, as with proposal_extras.type: adding an
-- observer and its channel must not require a schema migration.
--
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id BIGINT NOT NULL,
    proposal_id BIGINT,
    channel VARCHAR(40) NOT NULL,
    event_type VARCHAR(60) NOT NULL,
    payload TEXT NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_notifications_agency FOREIGN KEY (agency_id)
        REFERENCES agencies (id) ON DELETE CASCADE,
    CONSTRAINT fk_notifications_proposal FOREIGN KEY (proposal_id)
        REFERENCES proposals (id) ON DELETE CASCADE
);

CREATE INDEX idx_notifications_agency_sent_at ON notifications (agency_id, sent_at);
CREATE INDEX idx_notifications_proposal_id ON notifications (proposal_id);
