--
-- SIMULATED — no real money moves. Acceptance issues a contract and records
-- one 50 percent deposit in the same transaction. These checks preserve the
-- academic demo invariant even when a row is written outside the Java model.
--
CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id BIGINT NOT NULL,
    contract_id BIGINT NOT NULL,
    kind VARCHAR(20) NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    provider VARCHAR(40) NOT NULL,
    provider_ref VARCHAR(80) NOT NULL,
    status VARCHAR(20) NOT NULL,
    simulated BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    paid_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_payments_proposal FOREIGN KEY (proposal_id) REFERENCES proposals(id) ON DELETE CASCADE,
    CONSTRAINT fk_payments_contract FOREIGN KEY (contract_id) REFERENCES contracts(id) ON DELETE CASCADE,
    CONSTRAINT uq_payments_proposal_kind UNIQUE (proposal_id, kind),
    CONSTRAINT uq_payments_provider_ref UNIQUE (provider_ref),
    CONSTRAINT ck_payments_kind CHECK (kind IN ('DEPOSIT')),
    CONSTRAINT ck_payments_amount CHECK (amount > 0),
    CONSTRAINT ck_payments_provider CHECK (provider = 'SIMULATED'),
    CONSTRAINT ck_payments_status CHECK (status IN ('SIMULATED_PAID')),
    CONSTRAINT ck_payments_simulated CHECK (simulated = TRUE)
);
