--
-- Proposal PDFs retain the rendered bytes and their type beside the proposal.
-- The unique key allows regeneration to replace each document in place.
--
CREATE TABLE proposal_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    file_name VARCHAR(160) NOT NULL,
    content_type VARCHAR(60) NOT NULL,
    content BYTEA NOT NULL,
    size_bytes BIGINT NOT NULL,
    generated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_proposal_documents_proposal FOREIGN KEY (proposal_id) REFERENCES proposals(id) ON DELETE CASCADE,
    CONSTRAINT uq_proposal_documents_proposal_type UNIQUE (proposal_id, type),
    CONSTRAINT ck_proposal_documents_type CHECK (type IN ('PROPOSAL', 'CONTRACT', 'SCHEDULE')),
    CONSTRAINT ck_proposal_documents_size CHECK (size_bytes > 0)
);
