--
-- Persist clarification questions beside each brief so answers survive agent runs.
-- Resolution is atomic: an answer and its timestamp must always occur together.
--
CREATE TABLE brief_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brief_id BIGINT NOT NULL,
    code VARCHAR(60) NOT NULL,
    question VARCHAR(1000) NOT NULL,
    blocking BOOLEAN NOT NULL,
    status VARCHAR(20) NOT NULL,
    answer TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    resolved_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_brief_questions_brief FOREIGN KEY (brief_id) REFERENCES briefs(id) ON DELETE CASCADE,
    CONSTRAINT uq_brief_questions_brief_code UNIQUE (brief_id, code),
    CONSTRAINT ck_brief_questions_status CHECK (status IN ('OPEN', 'RESOLVED')),
    CONSTRAINT ck_brief_questions_resolution CHECK (
        (status = 'OPEN' AND answer IS NULL AND resolved_at IS NULL)
        OR (status = 'RESOLVED' AND answer IS NOT NULL AND resolved_at IS NOT NULL)
    )
);

CREATE INDEX idx_brief_questions_brief ON brief_questions(brief_id);
