-- V2__agency_user_client.sql
-- Core identity aggregates (project.txt section 9: Agencia -> Usuario, Cliente).
-- Tables and columns are in English; only content rows may be in Spanish.

CREATE TABLE agencies (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id  BIGINT NOT NULL,
    full_name  VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    role       VARCHAR(20) NOT NULL,
    owner_flag BOOLEAN,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_users_agency FOREIGN KEY (agency_id) REFERENCES agencies (id),
    CONSTRAINT uq_users_agency_email UNIQUE (agency_id, email),
    -- Business rule: exactly one owner per agency. owner_flag is TRUE on the
    -- owner row and NULL on staff, so UNIQUE(agency_id, owner_flag) blocks a
    -- second owner while allowing many staff (NULLs are distinct in a unique
    -- key). This emulates a partial unique index, which H2 (used by tests) and
    -- STORED generated columns cannot express portably across H2/PostgreSQL.
    CONSTRAINT uq_users_agency_owner UNIQUE (agency_id, owner_flag),
    CONSTRAINT ck_users_role CHECK (role IN ('OWNER', 'STAFF')),
    CONSTRAINT ck_users_owner_flag CHECK (owner_flag IS NULL OR role = 'OWNER')
);

CREATE INDEX idx_users_agency_id ON users (agency_id);

CREATE TABLE clients (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id  BIGINT NOT NULL,
    name       VARCHAR(255) NOT NULL,
    email      VARCHAR(255),
    company    VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_clients_agency FOREIGN KEY (agency_id) REFERENCES agencies (id),
    CONSTRAINT uq_clients_agency_email UNIQUE (agency_id, email)
);

CREATE INDEX idx_clients_agency_id ON clients (agency_id);
