-- V3__service_catalog_requirement_types.sql
-- Service catalog setup (project.txt section 2: the owner configures their
-- catalog of services; section 9 schema: ServicioCatalogo -> RequisitoTipo,
-- plus CategoriaServicio).
-- Tables and columns are in English; only content rows may be in Spanish.
--
-- Structure: one agency owns many service_categories; a category groups many
-- service_catalog entries; a catalog entry composes many requirement_types.
-- The catalog is the reference data the estimation step maps extracted
-- requirements against.

CREATE TABLE service_categories (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id  BIGINT NOT NULL,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_service_categories_agency FOREIGN KEY (agency_id) REFERENCES agencies (id),
    CONSTRAINT uq_service_categories_agency_name UNIQUE (agency_id, name)
);

CREATE INDEX idx_service_categories_agency_id ON service_categories (agency_id);

CREATE TABLE service_catalog (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id   BIGINT NOT NULL,
    category_id BIGINT,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_service_catalog_agency FOREIGN KEY (agency_id) REFERENCES agencies (id),
    -- A category is a shared label, not a lifecycle owner: removing it detaches
    -- its catalog entries instead of deleting them.
    CONSTRAINT fk_service_catalog_category FOREIGN KEY (category_id)
        REFERENCES service_categories (id) ON DELETE SET NULL,
    CONSTRAINT uq_service_catalog_agency_name UNIQUE (agency_id, name)
);

CREATE INDEX idx_service_catalog_agency_id ON service_catalog (agency_id);
CREATE INDEX idx_service_catalog_category_id ON service_catalog (category_id);

CREATE TABLE requirement_types (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_catalog_id BIGINT NOT NULL,
    name               VARCHAR(255) NOT NULL,
    description        VARCHAR(1000),
    -- Nullable so a catalog entry can be defined before the agency tunes effort.
    estimated_hours    NUMERIC(10, 2),
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    -- Requirement types are composed children of a catalog entry, so they share
    -- its lifecycle and are removed with it.
    CONSTRAINT fk_requirement_types_catalog FOREIGN KEY (service_catalog_id)
        REFERENCES service_catalog (id) ON DELETE CASCADE,
    CONSTRAINT uq_requirement_types_catalog_name UNIQUE (service_catalog_id, name)
);

CREATE INDEX idx_requirement_types_catalog_id ON requirement_types (service_catalog_id);

-- Delete-blocking contract for quoted items (project.txt section 9:
-- Propuesta -> ItemCotizado). Quoted items will reference requirement_types,
-- not the catalog entry directly, and that foreign key must be declared
-- ON DELETE RESTRICT in the proposal migration. Result: deleting a catalog
-- entry whose requirement types are already quoted fails at the database,
-- preserving quotation history. Until that migration exists there can be no
-- quoted item, so catalog deletion only cascades to unquoted requirement types.
