-- V4__rates_and_roles.sql
-- Rate table setup (project.txt section 2: the owner defines the agency's
-- hourly rate per role: designer, developer, PM...; section 9 schema:
-- Agencia -> Tarifa (rol -> $/hora)).
-- Tables and columns are in English; only content rows may be in Spanish.
--
-- Structure: one agency owns many roles; a role has many rates over time.
-- Amounts are COP (Colombian pesos) and stored as whole numbers, so the column
-- is BIGINT: COP has no decimals in practice and BIGINT avoids rounding drift.
-- Effective dating is optional: effective_from/effective_to may be NULL, which
-- means "always valid", so a role can have a single current rate.

CREATE TABLE roles (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id  BIGINT NOT NULL,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_roles_agency FOREIGN KEY (agency_id) REFERENCES agencies (id),
    CONSTRAINT uq_roles_agency_name UNIQUE (agency_id, name)
);

CREATE INDEX idx_roles_agency_id ON roles (agency_id);

CREATE TABLE rates (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id      BIGINT NOT NULL,
    role_id        BIGINT NOT NULL,
    cop_per_hour   BIGINT NOT NULL,
    -- Optional effective window: NULL bounds mean unbounded (always valid).
    effective_from TIMESTAMP WITH TIME ZONE,
    effective_to   TIMESTAMP WITH TIME ZONE,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    -- Rates are agency-scoped: the agency owns them and deleting the agency
    -- removes her rate table. A rate without its role is meaningless, so the
    -- role FK cascades as well (role is a composed child of the rate table).
    CONSTRAINT fk_rates_agency FOREIGN KEY (agency_id) REFERENCES agencies (id) ON DELETE CASCADE,
    CONSTRAINT fk_rates_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE,
    -- A rate must be positive: zero or negative $/hora is a configuration error.
    CONSTRAINT ck_rates_cop_positive CHECK (cop_per_hour > 0),
    -- Effective window must be coherent when both bounds are present.
    CONSTRAINT ck_rates_effective_window CHECK (
        effective_from IS NULL OR effective_to IS NULL OR effective_from < effective_to)
);

CREATE INDEX idx_rates_agency_id ON rates (agency_id);
CREATE INDEX idx_rates_role_id ON rates (role_id);
