-- V5__briefs.sql
-- Brief ingest (project.txt section 9 schema: Agencia -> Cliente -> Brief;
-- section 6 pattern 5a: input channels).
-- Tables and columns are in English; only content rows may be in Spanish.
--
-- A brief is the raw, messy text a client sends through some channel. The
-- input-channel Adapters normalize each channel into one Brief, so this table
-- stores the single canonical text the pipeline consumes plus the untouched
-- original payload for audit/provenance.

CREATE TABLE briefs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id   BIGINT NOT NULL,
    source      VARCHAR(20) NOT NULL,
    -- raw_text is the normalized brief: the one shape every channel produces.
    raw_text    TEXT NOT NULL,
    -- raw_payload is the original request as received, kept verbatim for audit.
    raw_payload TEXT NOT NULL,
    received_at TIMESTAMP WITH TIME ZONE NOT NULL,
    -- A brief belongs to a client. Briefs are quotation history, so deleting a
    -- client that has briefs is blocked (RESTRICT, the default) rather than
    -- silently erasing prior quotations.
    CONSTRAINT fk_briefs_client FOREIGN KEY (client_id) REFERENCES clients (id),
    -- The channel set is fixed here; a new channel is an additive change to
    -- this CHECK plus one new Adapter class.
    CONSTRAINT ck_briefs_source CHECK (source IN ('EMAIL', 'WHATSAPP', 'WEB_FORM'))
);

CREATE INDEX idx_briefs_client_id ON briefs (client_id);
