-- V6__extracted_requirements.sql
-- Requirement extraction (project.txt section 3 step 2: "Extraccion de
-- requisitos"; section 9 schema: Brief -> RequisitoExtraido).
-- Tables and columns are in English; only content rows may be in Spanish.
--
-- The pipeline's Extract handler turns the brief's messy text into structured
-- rows. Each row links the brief to a catalog requirement_type so the next
-- pipeline step (estimation) can map it to hours. confidence is the model's
-- own certainty; ambiguity_flag is derived from it in the domain layer so the
-- approval UI can list the clarification questions directly, without
-- recomputing the threshold. A stored generated column was avoided because
-- H2 (tests) and PostgreSQL cannot express it portably (see V2 for the same
-- reasoning).

CREATE TABLE extracted_requirements (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brief_id            BIGINT NOT NULL,
    requirement_type_id BIGINT NOT NULL,
    description         VARCHAR(1000) NOT NULL,
    -- Nullable: extraction may run before the estimation step tunes effort.
    estimated_hours     NUMERIC(10, 2),
    confidence          NUMERIC(5, 4) NOT NULL,
    ambiguity_flag      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    -- Extracted requirements are composed children of a brief, so they share
    -- its lifecycle and are removed with it.
    CONSTRAINT fk_extracted_requirements_brief FOREIGN KEY (brief_id)
        REFERENCES briefs (id) ON DELETE CASCADE,
    -- A catalog type anchors the requirement to the agency's offering; deleting
    -- a type that has been extracted is blocked (RESTRICT, the default) so
    -- quotation history stays traceable, mirroring the V3 contract.
    CONSTRAINT fk_extracted_requirements_type FOREIGN KEY (requirement_type_id)
        REFERENCES requirement_types (id),
    CONSTRAINT ck_extracted_requirements_confidence CHECK (confidence >= 0 AND confidence <= 1)
);

CREATE INDEX idx_extracted_requirements_brief_id ON extracted_requirements (brief_id);
CREATE INDEX idx_extracted_requirements_type_id ON extracted_requirements (requirement_type_id);
