-- V7__agent_executions_agent_steps.sql
-- Agent run log (project.txt section 2: "Ver el pipeline del agente ejecutarse
-- en vivo"; section 9 schema: Brief -> EjecucionAgente, with PasoAgente rows).
-- Tables and columns are in English; only content rows may be in Spanish.
--
-- Every pipeline run over a brief writes exactly one agent_executions row plus
-- one agent_steps row per Chain handler that executed. This is the live-demo
-- feed, so the write happens on both success and failure: an execution starts
-- in RUNNING, each step is appended as the handler finishes, and the run is
-- closed as SUCCEEDED or FAILED. The n+1 writes (1 execution + N steps) are
-- modelled as an aggregate so a run is never half-visible; the application
-- commits them together after the pipeline returns (or throws).
--
-- started_at / finished_at: finished_at stays NULL while RUNNING and is set on
-- the terminal transition. status on both tables is constrained to the fixed
-- set the domain knows about; a new status is an additive change to the CHECK.

CREATE TABLE agent_executions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brief_id      BIGINT NOT NULL,
    status        VARCHAR(20) NOT NULL,
    started_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    -- NULL until the run reaches a terminal status (SUCCEEDED or FAILED).
    finished_at   TIMESTAMP WITH TIME ZONE,
    -- Populated only when the run fails, so the panel can show why the chain
    -- stopped (e.g. a handler error or a low-confidence halt). Nullable to keep
    -- successful runs clean.
    error_message VARCHAR(1000),
    -- An execution is the log of one brief's run, so it is a composed child of
    -- the brief and is removed with it.
    CONSTRAINT fk_agent_executions_brief FOREIGN KEY (brief_id)
        REFERENCES briefs (id) ON DELETE CASCADE,
    CONSTRAINT ck_agent_executions_status
        CHECK (status IN ('RUNNING', 'SUCCEEDED', 'FAILED')),
    -- A terminal run must carry its finish time; a running one must not.
    CONSTRAINT ck_agent_executions_finished CHECK (
        (status = 'RUNNING' AND finished_at IS NULL)
        OR (status IN ('SUCCEEDED', 'FAILED') AND finished_at IS NOT NULL))
);

CREATE INDEX idx_agent_executions_brief_id ON agent_executions (brief_id);
CREATE INDEX idx_agent_executions_status ON agent_executions (status);

CREATE TABLE agent_steps (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id     BIGINT NOT NULL,
    -- handler is the Chain link that ran (e.g. ClassifyHandler), recorded by
    -- name so the timeline is human-readable without joining a registry table.
    handler          VARCHAR(100) NOT NULL,
    -- step_order is the position in the chain, unique per execution; the read
    -- API returns the timeline ordered by it.
    step_order       INT NOT NULL,
    -- Short, bounded summaries (not full prompts/responses) keep the live feed
    -- cheap to render; the full artifacts live in their own tables.
    input_summary    VARCHAR(1000),
    output_summary   VARCHAR(1000),
    duration_ms      BIGINT,
    status           VARCHAR(20) NOT NULL,
    -- Steps are composed children of an execution and share its lifecycle.
    CONSTRAINT fk_agent_steps_execution FOREIGN KEY (execution_id)
        REFERENCES agent_executions (id) ON DELETE CASCADE,
    CONSTRAINT uq_agent_steps_execution_order UNIQUE (execution_id, step_order),
    CONSTRAINT ck_agent_steps_status
        CHECK (status IN ('SUCCEEDED', 'FAILED', 'SKIPPED')),
    CONSTRAINT ck_agent_steps_order CHECK (step_order >= 0),
    CONSTRAINT ck_agent_steps_duration CHECK (duration_ms IS NULL OR duration_ms >= 0)
);

CREATE INDEX idx_agent_steps_execution_id ON agent_steps (execution_id);
