-- V8__proposals_quoted_items.sql
-- Proposal aggregate (project.txt section 9 schema: Brief -> Propuesta ->
-- ItemCotizado; section 6 pattern 2 Builder, pattern 9 State).
-- Tables and columns are in English; only content rows may be in Spanish.
--
-- A proposal is the priced offer built from a brief's extracted requirements.
-- It composes its quoted_items: a single save writes the proposal plus its
-- lines, and deleting the proposal removes them (ON DELETE CASCADE). Each line
-- references the extracted requirement it prices (RESTRICT default), so a
-- requirement already quoted cannot be deleted and quotation history stays
-- traceable, exactly as promised in V3.
--
-- subtotal / total are derived in the domain from the line totals, never set
-- independently by a caller. A stored generated column was avoided because H2
-- (tests) and PostgreSQL cannot express the per-row multiply-plus-sum portably
-- (same reasoning as V6); the aggregate recomputes both on every item change,
-- which makes a stored total that disagrees with its items impossible. total is
-- kept separate from subtotal so pricing decorators (urgency, discount) can
-- later adjust it while subtotal remains item-derived.

CREATE TABLE proposals (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brief_id    BIGINT NOT NULL,
    status      VARCHAR(20) NOT NULL,
    subtotal    NUMERIC(12, 2) NOT NULL,
    total       NUMERIC(12, 2) NOT NULL,
    -- Nullable until the agency commits to an expiry date.
    valid_until TIMESTAMP WITH TIME ZONE,
    -- Optional commercial fields, all nullable; the Builder fills them in.
    terms       TEXT,
    schedule    TEXT,
    extras      TEXT,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    -- A proposal is the priced offer for one brief and shares its lifecycle.
    CONSTRAINT fk_proposals_brief FOREIGN KEY (brief_id) REFERENCES briefs (id),
    CONSTRAINT ck_proposals_status CHECK (status IN (
        'RECEIVED', 'ANALYZING', 'QUOTED', 'IN_REVIEW', 'SENT',
        'NEGOTIATING', 'ACCEPTED', 'CONTRACT_ISSUED', 'REJECTED', 'EXPIRED')),
    CONSTRAINT ck_proposals_subtotal CHECK (subtotal >= 0),
    CONSTRAINT ck_proposals_total CHECK (total >= 0)
);

CREATE INDEX idx_proposals_brief_id ON proposals (brief_id);
CREATE INDEX idx_proposals_status ON proposals (status);

CREATE TABLE quoted_items (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id    BIGINT NOT NULL,
    requirement_id BIGINT NOT NULL,
    hours          NUMERIC(10, 2) NOT NULL,
    unit_price     NUMERIC(12, 2) NOT NULL,
    -- line_total is hours * unit_price, written by the domain, never supplied.
    line_total     NUMERIC(12, 2) NOT NULL,
    -- Quoted items are composed children of a proposal and share its lifecycle.
    CONSTRAINT fk_quoted_items_proposal FOREIGN KEY (proposal_id)
        REFERENCES proposals (id) ON DELETE CASCADE,
    -- A quoted requirement anchors the line to the brief's extraction; deleting
    -- it while quoted is blocked (RESTRICT, the default) to keep history.
    CONSTRAINT fk_quoted_items_requirement FOREIGN KEY (requirement_id)
        REFERENCES extracted_requirements (id),
    CONSTRAINT ck_quoted_items_hours CHECK (hours >= 0),
    CONSTRAINT ck_quoted_items_unit_price CHECK (unit_price >= 0),
    CONSTRAINT ck_quoted_items_line_total CHECK (line_total >= 0)
);

CREATE INDEX idx_quoted_items_proposal_id ON quoted_items (proposal_id);
CREATE INDEX idx_quoted_items_requirement_id ON quoted_items (requirement_id);
