-- V9__proposal_extras.sql
-- Structured extras applied on top of a proposal (project.txt section 9
-- schema: Propuesta -> Extra; section 6 pattern 6 Decorator).
-- Tables and columns are in English; only content rows may be in Spanish.
--
-- Each row records one extra that a price decorator applied to a proposal
-- (urgency +25%, discount -10%, extended warranty fee...). The columns match
-- the decorator contract exactly:
--   type             - the decorator's self-declared kind (e.g. 'URGENCY');
--                      deliberately NOT a CHECK/ENUM, so adding a new extra is a
--                      new decorator class only, with no migration change.
--   percent_or_fixed - the rate as a fraction for percentage extras (0.25 for
--                      +25%, 0.10 for -10%) or the flat fee for fixed extras.
--                      Always a non-negative magnitude; the sign lives in amount.
--   amount           - the computed signed money delta this extra contributed to
--                      the proposal's total. Negative for a discount.
--
-- Extras are composed children of the proposal: deleting the proposal removes
-- them (ON DELETE CASCADE), the same lifecycle style as quoted_items.
--
-- The proposals.extras TEXT column from V8 stays as the human-readable summary;
-- this table is the structured, auditable breakdown behind it.

CREATE TABLE proposal_extras (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id      BIGINT NOT NULL,
    type             VARCHAR(40) NOT NULL,
    percent_or_fixed NUMERIC(12, 2) NOT NULL,
    -- amount is the computed delta; a discount makes it negative, so no >= 0
    -- check here (unlike inputs). The proposal total itself is checked >= 0.
    amount           NUMERIC(12, 2) NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_proposal_extras_proposal FOREIGN KEY (proposal_id)
        REFERENCES proposals (id) ON DELETE CASCADE,
    -- Rate/fee magnitudes are never negative; direction is encoded in amount.
    CONSTRAINT ck_proposal_extras_value CHECK (percent_or_fixed >= 0)
);

CREATE INDEX idx_proposal_extras_proposal_id ON proposal_extras (proposal_id);
